### ISSUE TITLE
Missing containers.py

### ISSUE THREAD

**Issue by eswald** [tomerfiliba/construct3#2]
When importing construct3, I get an exception due to a missing construct3/lib/containers.py file:

```
$ python -c 'import construct3'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "construct3/__init__.py", line 3, in <module>
    from construct3.packers import (Packer, PackerError, Adapter, Struct, NamedPacker, Raw, Range, Bitwise, 
  File "construct3/packers.py", line 4, in <module>
    from construct3.lib.containers import Container
ImportError: No module named containers
```

Copying the construct/lib/container.py file from the construct 2 repository fixes the issue, but I'm guessing you have a file that simply hasn't been added to the repository.

**Comment by tomerfiliba** [comment]
oops, the lib/ directory was ignored by the default .gitignore that i used; fixed that now
